import logtrail
logtrail.logger.info("calling 'logtrail.logger.info'")
logtrail.logger.debug("calling 'logtrail.logger.debug'")
logtrail.logger.warn("calling 'logtrail.logger.warn'")
logtrail.logger.error("calling 'logtrail.logger.error'")
logtrail.logger.i("calling 'logtrail.logger.i'")
logtrail.logger.d("calling 'logtrail.logger.d'")
logtrail.logger.w("calling 'logtrail.logger.w'")
logtrail.logger.e("calling 'logtrail.logger.e'")
