import logtrail
logtrail.Logger.info("calling 'logtrail.logger.info'")
logtrail.Logger.debug("calling 'logtrail.logger.debug'")
logtrail.Logger.warn("calling 'logtrail.logger.warn'")
logtrail.Logger.error("calling 'logtrail.logger.error'")
logtrail.Logger.i("calling 'logtrail.logger.i'")
logtrail.Logger.d("calling 'logtrail.logger.d'")
logtrail.Logger.w("calling 'logtrail.logger.w'")
logtrail.Logger.e("calling 'logtrail.logger.e'")
